name: Test and Upload Results

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant Execute Permission
        run: |
          chmod +x ./gradlew
          chmod +x scripts/zip-test-results.sh

      - name: Run Tests
        run: ./gradlew test

      - name: Zip Test Results
        run: ./scripts/zip-test-results.sh

      - name: Upload Test Results Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-artifacts/test-results.zip